pipeline {
    agent any

    stages {
        stage('System Identity') {
            steps {
                sh 'hostname'
            }
        }
        stage('Server Date') {
            steps {
                sh 'date'
            }
        }
        stage('CPU Usage Details') {
            steps {
                sh 'lscpu'
            }
        }
    }
}
