pipeline {
       agent any

       stages{
           stage{'hostname'}{

             steps{

            sh 'hostname'
             }
           }
       stage{'Server-date'}{

         steps{
            sh'date'
         }
       }

stage{'CPU-Details'}{

         steps{
            sh'lscpu'
         }
       }

       }
}
